name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy-customer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g vercel
      - run: vercel deploy --prod --yes --cwd customer --token=${{ secrets.vcp_53gto32A2GsPA8Zx0lsoOc5hmtzsZLnV0Bbp4jmwEt1ettTdgH3oHvB6 }}
        env:
          VERCEL_ORG_ID: ${{ secrets.team_vLG8AdnT9wwHCzgEqMUfOgfG }}
          VERCEL_PROJECT_ID: ${{ secrets.prj_PKZoATBEbDYGTZ2ghn90vJEfvEf5 }}

  deploy-merchant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g vercel
      - run: vercel deploy --prod --yes --cwd merchant --token=${{ secrets.vcp_53gto32A2GsPA8Zx0lsoOc5hmtzsZLnV0Bbp4jmwEt1ettTdgH3oHvB6 }}
        env:
          VERCEL_ORG_ID: ${{ secrets.team_vLG8AdnT9wwHCzgEqMUfOgfG }}
          VERCEL_PROJECT_ID: ${{ secrets.prj_qBYw0XgEXjlyqN9jNTA410AAwcZ1 }}
