name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy-customer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g vercel
      - run: vercel deploy --prod --yes --cwd customer --token=${{ secrets.VERCEL_TOKEN }}

  deploy-merchant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g vercel
      - run: vercel deploy --prod --yes --cwd merchant --token=${{ secrets.VERCEL_TOKEN }}